version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: finalAssessment_postgres_container
    restart: always
    environment:
      POSTGRES_DB: finalAssessment_dms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: akash123
    ports:
      - "5433:5432"
    volumes:
      - /Users/akashgurnale2/Documents/FinalAssessment_MobileApp_AkashGurnale/DockerVolume

  springbootapp:
    image: finalassessment_app
    build: .
    container_name: finalAssessment_springboot_container
    restart: always
    depends_on:
      - postgres
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/finalAssessment_dms
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: akash123
